### ISSUE TITLE
realm with display name or HTML display name cannot be exported

### ISSUE THREAD

**Issue by justinc1** [justinc1/keycloak-fetch-bot#19]
Set realm display name or HTML display name, stacktrace is
```
publishing:  ci0-realm
** Client fetching:  clients
--> fetching:  roles
--> fetching:  identity-provider
** User federation fetching:  user-federations
--> fetching:  components
Traceback (most recent call last):
  File "/home/justin_cinkelj/devel/steampunk/ddd/keycloak-fetch-bot/.venv/bin/kcfetcher", line 8, in <module>
    sys.exit(main_cli())
  File "/home/justin_cinkelj/devel/steampunk/ddd/keycloak-fetch-bot/kcfetcher/main.py", line 58, in main_cli
    run(output_dir)
  File "/home/justin_cinkelj/devel/steampunk/ddd/keycloak-fetch-bot/kcfetcher/main.py", line 52, in run
    fetch_keycloak_objects.fetch(store)
  File "/home/justin_cinkelj/devel/steampunk/ddd/keycloak-fetch-bot/kcfetcher/fetch/generic.py", line 25, in fetch
    kc_objects = self._get_data()
  File "/home/justin_cinkelj/devel/steampunk/ddd/keycloak-fetch-bot/kcfetcher/fetch/generic.py", line 30, in _get_data
    kc_objects = self.all(kc)
  File "/home/justin_cinkelj/devel/steampunk/ddd/keycloak-fetch-bot/kcfetcher/fetch/generic.py", line 34, in all
    return list(filter(lambda fn: not fn[self.id] in self.black_list, kc.all()))
  File "/home/justin_cinkelj/devel/steampunk/ddd/keycloak-fetch-bot/kcfetcher/fetch/generic.py", line 34, in <lambda>
    return list(filter(lambda fn: not fn[self.id] in self.black_list, kc.all()))
KeyError: 'name'
```

**Comment by justinc1** [comment]
Same/similar stacktrace if in Login "Email as username" is enabled (first enable 'User registration')

**Comment by justinc1** [comment]
And same bug if Email settings are changed.
